datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://devops-prometheus-server:80
      isDefault: true
      access: proxy

#dashboards:
#  default:
#    prometheus-stats:
      # Ref: https://grafana.com/dashboards/2
#      gnetId: 2
#      revision: 2
#      datasource: Prometheus
#    spring-stats:
#      gnetId: 6756
#      revision: 2
#      datasource: Prometheus