INSERT INTO USERS (USER_ID, FIRSTNAME, SURNAME, EMAIL, PASSWORD, ENABLED, REGISTERED_ON) VALUES (31, 'John', 'Doe', 'jdoe@example.com', 'password123', 1, CURRENT_TIMESTAMP);
INSERT INTO USERS (USER_ID, FIRSTNAME, SURNAME, EMAIL, PASSWORD, ENABLED, REGISTERED_ON) VALUES (32, 'Mary', 'Doe', 'mdoe@example.com', 'password123', 1, CURRENT_TIMESTAMP);

INSERT INTO ROLES (ROLE_ID, ROLE) VALUES (21, 'TRAINEE');
INSERT INTO ROLES (ROLE_ID, ROLE) VALUES (22, 'ADMIN');
INSERT INTO ROLES (ROLE_ID, ROLE) VALUES (23, 'MANAGER');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (31, 21);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (32, 22);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (32, 23);


INSERT INTO COURSES (COURSE_ID, TITLE, IMAGE_NAME, ENABLED) VALUES (11, 'Course 1', 'image1.png', 1);

INSERT INTO USER_ASSIGNMENT (USER_ASSIGNMENT_ID, ASSIGNED_ON, DEADLINE, LAST_UPDATED, COURSE_ID, USER_ID, STATUS, current_stage_id) VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11, 31, 'INCOMPLETE', 0);